# Generated by Django 3.1.4 on 2020-12-06 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_sales', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='employee.employee')),
                ('products', models.ManyToManyField(through='product.ProductsSales', to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productssales',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_sales', to='product.sale'),
        ),
    ]
