# Generated by Django 3.1.4 on 2020-12-06 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=25)),
                ('region_code', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
            ],
            options={
                'unique_together': {('country_code', 'region_code', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=75)),
                ('second_surname', models.CharField(max_length=75)),
                ('number', models.IntegerField()),
                ('birthdate', models.DateField(null=True)),
                ('date_of_admission', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('sector', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('telephone', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.telephone')),
            ],
        ),
    ]
